# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'books.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector
mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="",
   database = "Books"
  
)


class Ui_bookentry(object):
    def __init__(self):
        self.I1 = 0
        self.I2= 0
        self.I3 = 0
        self.I4 = 0
    def setupUi(self, bookentry):
        bookentry.setObjectName("bookentry")
        bookentry.resize(780, 533)
        self.centralwidget = QtWidgets.QWidget(bookentry)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 150, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(310, 150, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.U1 = QtWidgets.QPushButton(self.centralwidget)
        self.U1.setGeometry(QtCore.QRect(440, 150, 75, 23))
        self.U1.setObjectName("U1")
        self.D1 = QtWidgets.QPushButton(self.centralwidget)
        self.D1.setGeometry(QtCore.QRect(530, 150, 75, 23))
        self.D1.setObjectName("D1")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(120, 150, 100, 22))
        self.comboBox.setObjectName("comboBox")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 150, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        bookentry.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(bookentry)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 780, 21))
        self.menubar.setObjectName("menubar")
        bookentry.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(bookentry)
        self.statusbar.setObjectName("statusbar")
        bookentry.setStatusBar(self.statusbar)

        self.retranslateUi(bookentry)
        QtCore.QMetaObject.connectSlotsByName(bookentry)

    def retranslateUi(self, bookentry):
        _translate = QtCore.QCoreApplication.translate
        bookentry.setWindowTitle(_translate("bookentry", "bookdetails"))
        self.label.setText(_translate("bookentry", "QTY"))
        self.U1.setText(_translate("bookentry", "UPDATE"))
        self.D1.setText(_translate("bookentry", "DELETE"))
        self.label_2.setText(_translate("bookentry", "SUBJECTS"))
        self.comboBox.addItem("MATHS")
        self.comboBox.addItem("SCIENCE")
        self.comboBox.addItem("HINDI")
        self.comboBox.addItem("ENGLISH")
        self.comboBox.addItem("SOCIAL")
        self.comboBox.addItem("SANSKRIT")
        self.U1.clicked.connect(self.book)
        # self.D1.clicked.connect(self.dell)

    def book(self):
        self.I1 = self.comboBox.currentText()
        self.I2 = int(self.lineEdit.text())
        mycursor = mydb.cursor()
        sql = "INSERT INTO details (BookName , Qty) VALUES(%s,%s)"
        val = [self.I1,self.I2]
        mycursor.execute(sql,val)
        mydb.commit()
    # def dell(self):
    #     self.I1 = self.comboBox.currentText()
    #     self.I3 = int(self.lineEdit.text())
    #     self.I4 = str(self.I2 - self.I3)
    #     sql = "UPDATE details SET Oty = self.I4 WHERE bookname = self.I1"
    #     mycursor = mydb.cursor()
    #     mycursor.execute(sql)
    #     mydb.commit()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    bookentry = QtWidgets.QMainWindow()
    ui = Ui_bookentry()
    ui.setupUi(bookentry)
    bookentry.show()
    sys.exit(app.exec_())
