# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'keyword12.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector
from books import *
mydb = mysql.connector.connect(

  host="localhost",
  user="root",
  password="",
  database = "Library" 
  
)


class Ui_PORTALWINDOW(object):
    def setupUi(self, PORTALWINDOW):
        PORTALWINDOW.setObjectName("PORTALWINDOW")
        PORTALWINDOW.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(PORTALWINDOW)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 631, 451))
        self.label.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.T1 = QtWidgets.QLineEdit(self.centralwidget)
        self.T1.setGeometry(QtCore.QRect(330, 100, 200, 20))
        self.T1.setObjectName("T1")
        self.T2 = QtWidgets.QLineEdit(self.centralwidget)
        self.T2.setGeometry(QtCore.QRect(330, 150, 200, 20))
        self.T2.setObjectName("T2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 100, 150, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 160, 150, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.B1 = QtWidgets.QPushButton(self.centralwidget)
        self.B1.setGeometry(QtCore.QRect(230, 220, 75, 23))
        self.B1.setObjectName("B1")
        PORTALWINDOW.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PORTALWINDOW)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        PORTALWINDOW.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PORTALWINDOW)
        self.statusbar.setObjectName("statusbar")
        PORTALWINDOW.setStatusBar(self.statusbar)

        self.retranslateUi(PORTALWINDOW)
        QtCore.QMetaObject.connectSlotsByName(PORTALWINDOW)

    def retranslateUi(self, PORTALWINDOW):
        _translate = QtCore.QCoreApplication.translate
        PORTALWINDOW.setWindowTitle(_translate("PORTALWINDOW", "portal"))
        self.label_2.setText(_translate("PORTALWINDOW", "Enter Email Id:"))
        self.label_3.setText(_translate("PORTALWINDOW", "Enter Password:"))
        self.B1.setText(_translate("PORTALWINDOW", "SUBMIT"))
        self.B1.clicked.connect(self.stor)
        self.B1.clicked.connect(PORTALWINDOW.close)
    def stor(self):
        mycursor = mydb.cursor()
        I1 = self.T1.text()
        I2 = self.T2.text()
        mycursor.execute("SELECT EmailId,Password FROM signup")
        myresult = mycursor.fetchall()
        A = []
        for i in myresult:
            A.append(i)
            print(A)
        for i in A:
            print(A)
            sm = 0
            if (I1 == i[0] and I2 == i[1] ):
                sm = sm + 1
            if sm > 0:
                print("Login Acess")
                self.bookwin = QtWidgets.QMainWindow()
                self.ui = Ui_bookentry()
                self.ui.setupUi(self.bookwin)
                self.bookwin.show()
            else:
                print("Login Denied")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PORTALWINDOW = QtWidgets.QMainWindow()
    ui = Ui_PORTALWINDOW()
    ui.setupUi(PORTALWINDOW)
    PORTALWINDOW.show()
    sys.exit(app.exec_())
